name: Automate Python Script

on:
  schedule:
    - cron: '0 0 * * *' # Ejecuta diariamente a medianoche UTC.
  workflow_dispatch: # Permite ejecución manual.

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Paso 4: Ejecutar el script
      - name: Run script
        id: run-script
        run: |
          python importacion.py > output.log
          cat output.log
        env:
          DSN: ${{ secrets.DSN }}

      # Paso 5: Enviar correo con el resumen
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "GitHub Actions Workflow: Resumen de Ejecución"
          body: |
            Hola,

            Aquí está el resumen de la ejecución del workflow:

            ${{ steps.run-script.outputs.terminal_output }}

            Gracias,
            GitHub Actions
          to: frentz233@gmail.com
          from: GitHub Actions Bot <${{ secrets.EMAIL_USER }}>

      # Paso 6 (Opcional): Subir el archivo de salida como artefacto
      - name: Upload execution log
        uses: actions/upload-artifact@v3
        with:
          name: execution-summary
          path: output.log
